version: "3.9"

services:
  angular_app:
    container_name: angular_app
    image: chn-angular_app:1.0.0
    build: ./angular/my-front-app/
    ports:
      - "4200:4200"
    depends_on:
      - java_app

  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:oracle:thin:@java_db:1521:xe
      - DATABASE_USERNAME=RRHH
      - DATABASE_PASSWORD=admin
      - DATABASE_JDBC=oracle.jdbc.OracleDriver

  java_db:
    container_name: java_db
    image: oracle/database:11.2.0.2-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=true
      - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
      - ORACLE_PASSWORD=admin
    volumes:
      - oracle_data:/u01/app/oracle

volumes:
  oracle_data:

